//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcValidation.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsCtRx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsCtRx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcValidation.Resources.Controllers.ErrorsCtRx", typeof(ErrorsCtRx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string AccountController_ChangePassword_Error {
            get {
                return ResourceManager.GetString("AccountController_ChangePassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string AccountController_CheckEntryAndRetry_Error {
            get {
                return ResourceManager.GetString("AccountController_CheckEntryAndRetry_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string AccountController_Default_Error {
            get {
                return ResourceManager.GetString("AccountController_Default_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists. Please enter a different email..
        /// </summary>
        public static string AccountController_DuplicateEmail_Error {
            get {
                return ResourceManager.GetString("AccountController_DuplicateEmail_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists. Please enter a different user name..
        /// </summary>
        public static string AccountController_DuplicateUserName_Error {
            get {
                return ResourceManager.GetString("AccountController_DuplicateUserName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provided is invalid. Please check the value and try again..
        /// </summary>
        public static string AccountController_Invalid_Error {
            get {
                return ResourceManager.GetString("AccountController_Invalid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieval answer.
        /// </summary>
        public static string AccountController_InvalidAnswer_Error {
            get {
                return ResourceManager.GetString("AccountController_InvalidAnswer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieval question.
        /// </summary>
        public static string AccountController_InvalidQuestion_Error {
            get {
                return ResourceManager.GetString("AccountController_InvalidQuestion_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string AccountController_LogOn_Error {
            get {
                return ResourceManager.GetString("AccountController_LogOn_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error..
        /// </summary>
        public static string AccountController_Provider_Error {
            get {
                return ResourceManager.GetString("AccountController_Provider_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled..
        /// </summary>
        public static string AccountController_UserRejected_Error {
            get {
                return ResourceManager.GetString("AccountController_UserRejected_Error", resourceCulture);
            }
        }
    }
}
