//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcValidation.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsMdRx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsMdRx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcValidation.Resources.Models.ErrorsMdRx", typeof(ErrorsMdRx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string AccountController_ChangePassword_Error {
            get {
                return ResourceManager.GetString("AccountController_ChangePassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password Error.
        /// </summary>
        public static string ConfirmNewPassword_Error {
            get {
                return ResourceManager.GetString("ConfirmNewPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword Error.
        /// </summary>
        public static string ConfirmPassword_Error {
            get {
                return ResourceManager.GetString("ConfirmPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password Error.
        /// </summary>
        public static string CurrentPassword_Error {
            get {
                return ResourceManager.GetString("CurrentPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Error.
        /// </summary>
        public static string Email_Error {
            get {
                return ResourceManager.GetString("Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Error.
        /// </summary>
        public static string NewPassword_Error {
            get {
                return ResourceManager.GetString("NewPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Error.
        /// </summary>
        public static string Password_Error {
            get {
                return ResourceManager.GetString("Password_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Error.
        /// </summary>
        public static string UserName_Error {
            get {
                return ResourceManager.GetString("UserName_Error", resourceCulture);
            }
        }
    }
}
